### ISSUE TITLE
Server cannot compile run

### ISSUE THREAD

**Issue by Kojima648** [Blitzy/unity-radialcontroller#2]
Some files are lost, resulting in many errors of missing references.

**Comment by Blitzy** [comment]
Can you be more specific about what error(s) you are getting?

**Comment by Kojima648** [comment]
Git ignored the vs project's solution and configuration files, and I couldn't run properly. You can clone the warehouse and try to run it

**Comment by Kojima648** [comment]
where config in the interface in form1 cannot be found, and the referenced controller field name is not correct
